services:
  - type: web
    name: mental-health-fitness-tracker
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MPLCONFIGDIR
        value: /tmp/matplotlib
    healthCheckPath: /
    autoDeploy: true
    plan: free
