services:
  - type: web
    name: mental-health-fitness-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.7
    healthCheckPath: /
    autoDeploy: true
    plan: free
